redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
allow-lan: true
external-controller: 0.0.0.0:9090
bind-address: "*"
geodata-mode: true
geodata-loader: standard
dns:
  enable: true
  prefer-h3: false
  use-hosts: true
  use-system-hosts: true
  respect-rules: false
  listen: 0.0.0.0:1053
  ipv6: true
  default-nameserver:
    - 116.116.116.116
    - 221.5.88.88
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - '*.lan'
  nameserver:
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
  fallback:
    - https://dns.google/dns-query
    - https://dns64.dns.google/dns-query
    - https://dns.cloudflare.com/dns-query
    - https://cloudflare-dns.com/dns-query
  nameserver-policy:
    "geosite:cn":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
  proxy-server-nameserver:
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
  direct-nameserver:
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
  direct-nameserver-follow-policy: true
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
sniffer:
  enable: true
  parse-pure-ip: true
tun:
  enable: true
  stack: system
  device: utun
  dns-hijack:
    - tcp://any:53
  gso: true
  gso-max-size: 65536
  auto-route: false
  auto-detect-interface: false
  auto-redirect: false
  strict-route: false
profile:
  store-selected: true
listeners:
  - name: mixed5
    type: mixed
    port: 50055
    listen: 0.0.0.0
    udp: true
    proxy: ðŸ‡ºðŸ‡¸ Oracle-US-SanJose-Vless-Reality-Vision
  - name: mixed6
    type: mixed
    port: 50056
    listen: 0.0.0.0
    udp: true
    proxy: ðŸ‡ºðŸ‡¸ Oracle-US-SanJose-Vless-Reality-GRPC
  - name: mixed7
    type: mixed
    port: 50057
    listen: 0.0.0.0
    udp: true
    proxy: DIRECT
